apiVersion: v1
kind: Config
clusters:
  - name: "kuba-cluster"
    cluster:
      server: "https://rancher.cloud.e-infra.cz/k8s/clusters/c-m-qvndqhf6"

users:
  - name: "kuba-cluster"
    user:
      token: "kubeconfig-u-54o4bdafc6txzsm:6k87rzqmbbgzmp6xc9dx44lplt7n5ngshwc6nzrzfb7l66vhqrnx8x"


contexts:
  - name: "kuba-cluster"
    context:
      user: "kuba-cluster"
      cluster: "kuba-cluster"
      namespace: "janik-ns"

current-context: "kuba-cluster"
